import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	designSidebar: [{ type: "autogenerated", dirName: "design" }],
	contributingSidebar: [{ type: "autogenerated", dirName: "contributing" }],
	usageSidebar: [{ type: "autogenerated", dirName: "usage" }],
};

export default sidebars;
